### ISSUE TITLE
在eslint8.56.0中使用时报错：使用了被移除的属性

### ISSUE THREAD

**Issue by Azir-11** [soybeanjs/eslint-config#3]
Error: Invalid Options:
- Unknown options: reportUnusedDisableDirectives
- 'reportUnusedDisableDirectives' has been removed. Please use the 'overrideConfig.linterOptions.reportUnusedDisableDirectives' option instead.

Error: Invalid Options:
- Unknown options: reportUnusedDisableDirectives
- 'reportUnusedDisableDirectives' has been removed. Please use the 'overrideConfig.linterOptions.reportUnusedDisableDirectives' option instead.

**Comment by honghuangdc** [comment]
eslint-config-soybeanjs是旧版的包

**Comment by honghuangdc** [comment]
是新版的有些问题吗

**Comment by honghuangdc** [comment]
https://github.com/soybeanjs/eslint-flat-config

**Comment by Azir-11** [comment]
在新的main里，package.json使用的还是
`"@soybeanjs/eslint-config": "1.1.6"`
是否需要手动将其更新为嘞
`soybeanjs/eslint-flat-config`

**Comment by honghuangdc** [comment]
@soybeanjs/eslint-config 这个就是新版的包

**Comment by honghuangdc** [comment]
旧版的是 eslint-config-soybeanjs

**Comment by Azir-11** [comment]
感谢，把这个依赖删掉重新安装之后没有报错了
